### PR TITLE
fixes #71 #46 -  Segmentation fault when opening the Blockchain page repeteadly

### LINKED ISSUE #46: Backend to manage the blockchain
**Feature description:**
Need a backend to manage the blockchain. See the following image:
Blockchain

**Possible implementation:**

### LINKED ISSUE #71: Segmentation fault when opening the Blockchain page repeteadly
**How to reproduce it?**
First, go offline.  
Second, this pseudocode illustrates the procedure:  
```c
for (;;) {
    openBlockchainPage();
    back();
}
```
No too many iterations are required in order to reproduce the bug.
You may want to wait for merging of PR #70.

The output is the following:  
```
Get http://node.skycoin.net/api/v1/last_blocks?num=1: dial tcp: lookup node.skycoin.net on 127.0.0.53:53: server misbehaving
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f9d99a8f200]

runtime stack:
runtime.throw(0x9a4150, 0x2a)
        /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8822d0, 0xc420143f18, 0x84e6dc)
        /usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x64 fp=0xc420143ee8 sp=0xc420143eb0 pc=0x4571b4
github.com/therecipe/qt/gui._Cfunc_QGuiApplication_QGuiApplication_Exec(0x0)
        _cgo_gotypes.go:1360 +0x49 fp=0xc420143f18 sp=0xc420143ee8 pc=0x822ed9
github.com/therecipe/qt/gui.(*QGuiApplication).Exec(0xc42000e018, 0x9f49e0)
        /home/lateo/go/src/github.com/therecipe/qt/gui/gui-minimal.go:1668 +0x22 fp=0xc420143f30 sp=0xc420143f18 pc=0x82f4f2
main.main()
        /home/lateo/go/src/github.com/fibercrypto/FiberCryptoWallet/main.go:43 +0x227 fp=0xc420143f88 sp=0xc420143f30 pc=0x853b47
runtime.main()
        /usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc420143fe0 sp=0xc420143f88 pc=0x481152
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420143fe8 sp=0xc420143fe0 pc=0x4ab2f1

goroutine 67 [select]:
net/http.(*persistConn).writeLoop(0xc420246240)
        /usr/lib/go-1.10/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1238 +0x97f

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7f9d9ab06f00, 0x72, 0xc42004e760)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42024ea98, 0x72, 0xffffffffffffff00, 0x9f58c0, 0xf487f0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42024ea98, 0xc4204dd000, 0x1000, 0x1000)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42024ea80, 0xc4204dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42024ea80, 0xc4204dd000, 0x1000, 0x1000, 0xc42004e898, 0x465686, 0x7f9d9ab56260)
        /usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42009c108, 0xc4204dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc4201ccdb0, 0x7f9d9ab0f5f8, 0xc42009c108, 0x5, 0xc42009c108, 0xc42004ea90)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc420095880, 0x9b3b17, 0xc4200959a0, 0x4a7510)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc420095880, 0xc420135000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:1156 +0x100
net/http.(*persistConn).Read(0xc4200abd40, 0xc420135000, 0x1000, 0x1000, 0xc42004eb98, 0x4592a5, 0xc4200742a0)
        /usr/lib/go-1.10/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc42006a180)
        /usr/lib/go-1.10/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc42006a180, 0x1, 0x0, 0x0, 0x1, 0xc420074540, 0x0)
        /usr/lib/go-1.10/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc4200abd40)
        /usr/lib/go-1.10/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1237 +0x95a

goroutine 36 [select]:
net/http.(*persistConn).writeLoop(0xc4200abd40)
        /usr/lib/go-1.10/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1238 +0x97f

goroutine 46 [IO wait]:
internal/poll.runtime_pollWait(0x7f9d9ab06bc0, 0x72, 0xc42004a760)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201bca18, 0x72, 0xffffffffffffff00, 0x9f58c0, 0xf487f0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201bca18, 0xc420389000, 0x1000, 0x1000)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201bca00, 0xc420389000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201bca00, 0xc420389000, 0x1000, 0x1000, 0x20, 0x28, 0xc4201cd3b0)
        /usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e148, 0xc420389000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc4201cd140, 0x7f9d9ab0f5f8, 0xc42000e148, 0x5, 0xc42000e148, 0xc42004aa90)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc420012700, 0x9b3b17, 0xc420012820, 0x4a7510)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc420012700, 0xc42037c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:1156 +0x100
net/http.(*persistConn).Read(0xc4200aa240, 0xc42037c000, 0x1000, 0x1000, 0xc42004ab98, 0x4592a5, 0xc420074e40)
        /usr/lib/go-1.10/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc42006ac00)
        /usr/lib/go-1.10/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc42006ac00, 0x1, 0x0, 0x0, 0x1, 0xc4200750e0, 0x0)
        /usr/lib/go-1.10/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc4200aa240)
        /usr/lib/go-1.10/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1237 +0x95a

goroutine 47 [select]:
net/http.(*persistConn).writeLoop(0xc4200aa240)
        /usr/lib/go-1.10/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1238 +0x97f

goroutine 66 [IO wait]:
internal/poll.runtime_pollWait(0x7f9d9ab06af0, 0x72, 0xc42026d9a8)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42024f418, 0x72, 0xffffffffffffff00, 0x9f58c0, 0xf487f0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42024f418, 0xc42038f000, 0x1000, 0x1000)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42024f400, 0xc42038f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42024f400, 0xc42038f000, 0x1000, 0x1000, 0x4a7510, 0xc420000180, 0x4)
        /usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42009c0f8, 0xc42038f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*persistConn).Read(0xc420246240, 0xc42038f000, 0x1000, 0x1000, 0xc42026db98, 0x4592a5, 0xc42017e960)
        /usr/lib/go-1.10/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc42006afc0)
        /usr/lib/go-1.10/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc42006afc0, 0x1, 0x0, 0x0, 0x0, 0xc420075440, 0x0)
        /usr/lib/go-1.10/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc420246240)
        /usr/lib/go-1.10/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1237 +0x95a

goroutine 62 [IO wait]:
internal/poll.runtime_pollWait(0x7f9d9ab06a20, 0x72, 0xc42004b760)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42024fa18, 0x72, 0xffffffffffffff00, 0x9f58c0, 0xf487f0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42024fa18, 0xc420149000, 0x1000, 0x1000)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42024fa00, 0xc420149000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42024fa00, 0xc420149000, 0x1000, 0x1000, 0x20, 0x28, 0xc420500240)
        /usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42009c120, 0xc420149000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc420087920, 0x7f9d9ab0f5f8, 0xc42009c120, 0x5, 0xc42009c120, 0xc42004ba90)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc420094e00, 0x9b3b17, 0xc420094f20, 0x4a7510)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc420094e00, 0xc4203fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/crypto/tls/conn.go:1156 +0x100
net/http.(*persistConn).Read(0xc420246360, 0xc4203fb000, 0x1000, 0x1000, 0xc42004bb98, 0x4592a5, 0xc420075320)
        /usr/lib/go-1.10/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc4203ee480)
        /usr/lib/go-1.10/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc4203ee480, 0x1, 0x0, 0x0, 0x1, 0xc420075740, 0x0)
        /usr/lib/go-1.10/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc420246360)
        /usr/lib/go-1.10/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1237 +0x95a

goroutine 63 [select]:
net/http.(*persistConn).writeLoop(0xc420246360)
        /usr/lib/go-1.10/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.10/src/net/http/transport.go:1238 +0x97f
```

### PR DESCRIPTION
**Pull request by lagcleaner**
# Fixes:
Fixes #71 
Fixes #46 

# Changes:
- Instantiate the blockchain backend model in the `GeneralStackView` page instead of `Blockchain` page.
- Add an `update()` function to the backend model. This function is used to update the view.

### CODE REVIEW

**Comment by stdevMac** [comment]
@stdevlag Pls what are the changes you are applying to solve the bugs? Modify PR description pls

**Review by stdevCrow — APPROVED** [review]

**Review by stdevMac — CHANGES_REQUESTED** [review]
@stdevCrow pls remove `*moc*` files

**Comment by olemis** [comment]
Travis failure . Please fix before merge .

**Comment by stdevCrow** [comment]
> @stdevCrow pls remove `*moc*` files

This branch (simelo:stdevlag_t46_Backend_to_manage_the_blockchain) belongs to @stdevLag, not me.

**Pull request merged**
