### PR TITLE
Fixes #124 - Need asynchronous network operations and a busy indicator in the UI

### LINKED ISSUE #124: Need asynchronous network operations and a busy indicator in the UI
**Feature description**
Networking operations are hanging the UI. We need asynchronous networking and a busy indicator to inform the user that a operation is being done in the backend.

**Possible implementation**
- [x] Do the networking asynchronously (everybody)
- [x] Add a boolean property `busy` to all objects that perform such asynchronously operations (everybody)
- [x] Tell the user that an operation is being done in the backend (@lateo96)

### PR DESCRIPTION
**Pull request by stdevCrow**
# Fixes #124 - Need asynchronous network operations and a busy indicator in the UI

**Changes:**
- Add a `BusyIndicator`

**Does this change need to mentioned in CHANGELOG.md?**
No

**Requires changes in protobuff specs?**
No

**Requires testing**
Yes

### CODE REVIEW

**Review by stdevMac — APPROVED** [review]

**Comment by stdevCrow** [comment]
About asynchronous operations:
https://github.com/therecipe/qt/issues/840
https://github.com/therecipe/examples/blob/40390d02efe954eb840b680dd2d4ae48a27e1453/advanced/widgets/goroutine/main.go#L48

**Comment by stdevCrow** [comment]
@stdevCrow @marcosmaceo @mauricio1802 and others 👆

**Comment by stdevCrow** [comment]
@stdevCrow The issue is a discussion about using goroutines in therecipe/qt, and the example is... well... an example.

**Comment by stdevCrow** [comment]
@stdevCrow At that not work, you can always take a look at the Qt multithreading API:
https://doc.qt.io/qt-5/qtconcurrent-index.html
https://doc.qt.io/qt-5/qtconcurrentrun.html

**Review by stdevMac — APPROVED** [review]

**Pull request merged**
