### PR TITLE
add Spanish Translation to FiberCryptoWallet

### LINKED ISSUE #289: Add spanish language
- Add spanish tranlation for fibercryptowallet

### PR DESCRIPTION
**Pull request by rlsalgueiro**
Fixes #289

**Changes:**
- Adding Spanish translation

### CODE REVIEW

**Comment by olemis** [comment]
@rlsalgueiro pls add the number of the issue fixed by these changes , thnx in advance

**Review by olemis — CHANGES_REQUESTED** [review]
Needs a line in project CHANGELOG

**Comment by rlsalgueiro** [comment]
> @rlsalgueiro pls add the number of the issue fixed by these changes , thnx in advance

I can't find any issue for the Spanish translation. Can I create it?

**Comment by olemis** [comment]
@rlsalgueiro oh !

**Pull request merged**
